config/routes.rb
Rails.application.routes.draw do

  #Root
  root 'home#traffic_control'

  #Landing
  get "landing", to: "home#landing", as: :landing

  #Campaigns
  resources :campaigns do
    resources :topics do
      resources :posts, except: [:edit]
      resources :user_images
    end
  end

  #Contact
  post 'contact', to: 'contacts#create'
  
  #Users
  get 'warpgate', to: 'user_sessions#new', as: :warpgate
  post 'logout', to: 'user_sessions#destroy', as: :logout
  resources :users
  resources :user_sessions, except: [:update, :edit]
  resources :password_resets

  #Participated Campaigns
  get 'participated', to: 'participated_campaigns#index', as: :participated

  #Oauth
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  delete "oauth/:provider", to: "oauths#destroy", as: :delete_oauth

  #Admin Panel
  namespace :admin do
    get 'dashboard', to: 'dashboard#index', as: :dashboard
    resources :options, only: [:edit, :update]
    resources :reward_transactions, only: [:edit, :update]
    resources :featureds
    resources :campaigns do
      resources :topics
    end
    resources :announcements
    resources :users
  end
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  include Campaigns::Filters
  include Campaigns::Invitations
  extend Campaigns::Filters::ClassMethods
  extend Campaigns::Invitations::ClassMethods

  acts_as_taggable_on :categories, :invitations
  store_accessor :criteria

  has_many :topics
  has_many :posts
  has_many :reward_transactions
  has_one :featured, as: :featurable
  validates :title, :description, presence: true
  validate :at_least_one_topic_required
  validates_size_of :image, maximum: 5.megabytes, messaage: 'should be less than 5MB'
  validates_size_of :banner, maximum: 5.megabytes, messaage: 'should be less than 5MB'

  enum language: [:unspecified, :chinese, :english, :malay]

  accepts_nested_attributes_for :topics, allow_destroy: true
  mount_uploader :image, ImageUploader
  mount_uploader :banner, ImageUploader
  
  def at_least_one_topic_required
    return if topics.present?
    errors.add(:topic, 'is missing. At least one topic is required.')
  end
end

app/models/concerns/campaigns/filters.rb
module Campaigns::Filters

  module ClassMethods
    def targeted_at(user)
      select do |campaign|
        campaign.conditions?(user)
      end
    end
  end

  def conditions?(user)
    [
      private?,
      started?,
      active?,
      matching_interests?(user)
    ].all?
  end

  def private?
    self.private == false
  end

  def active?
    end_date >= Date.today
  end

  def started?
    start_date <= Date.today
  end

  def matching_interests?(user)
    category_list.blank? || match_user_interests(user, "primary_interest_list")
  end

  def match_user_interests(user, method)
    user.send(method).present? && user.send(method).any? { |interest| category_list.include?(interest) }
  end
end

app/models/concerns/campaigns/invitations.rb
module Campaigns::Invitations

  module ClassMethods
    def invited?(user)
      select do |campaign|
        campaign.has_user_invited?(user)
      end
    end
  end

  def has_user_invited?(user)
    self.private && (user.name.present? && invitation_list.include?(user.name)) && end_date > Date.today
  end
end

app/controllers/admin/campaigns_controller.rb
class Admin::CampaignsController < AdminController
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]
  before_action :set_platform_options, only: [:new, :edit]

  def index
    @campaigns = Campaign.order("created_at DESC")
  end

  def new
    @campaign = Campaign.new
  end

  def create
    @campaign = Campaign.new(campaign_params)
    if @campaign.save
      flash[:notice] = "Campaign created"
      redirect_to [:admin, @campaign]
    else
      flash[:error] = "Error creating campaign"
      render action: 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @campaign.update(campaign_params)
      flash[:notice] = "campaign updated"
      redirect_to [:admin, @campaign]
    else
      flash[:error] = "error updating"
      render action: 'edit'
    end
  end

  def destroy
    if @campaign.destroy
      flash[:error] = 'deleted'
      redirect_to admin_campaigns_path
    else
      flash[:error] = 'error'
    end
  end

  private

  def set_platform_options
    @options = Option.first
  end

  def set_campaign
    @campaign = Campaign.find(params[:id])
  end

  def campaign_params
    params.require(:campaign).permit(:status, :image, :banner, :start_date, :end_date, :title, :invitation_list,
                                     :description, :organizer, :category_list, :language, :private, :reward, :refcode,
                                     topics_attributes: [ :id, :_destroy, :title, :num_of_shares, { social_media_list: [] },
                                       :description, default_images_attributes: [ :topic_id, :storage, :id, :_destroy ] ])
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  require 'will_paginate/array'
  
  before_action :require_login, only: :index
  respond_to :js, :html

  def index
    campaigns = CampaignDecorator.wrap(Campaign.order("created_at DESC").targeted_at(current_user))
    @campaigns = campaigns.paginate(page: params[:page], per_page: 12)

    respond_with(@campaign)
  end

  def show
    campaign = Campaign.find(params[:id])

    authorize campaign
    @campaign = CampaignDecorator.new(campaign)
  end
end

app/helpers/campaign_helper.rb
module CampaignHelper
  def number_of_shares(topic)
    topic.num_of_shares - current_user.posts.where(topic_id: topic.id, status: "active").count
  end

  def campaign_reward(campaign)
    if current_user
      score = current_user.social_score.viral_score
      campaign.reward * Tier::RewardMultiplier.new.get(score)
    else
      "Up to #{campaign.reward}"
    end
  end

  def reward_range(campaign)
    lowest = campaign.reward * Tier::RewardMultiplier.new.get(1)
    highest = campaign.reward * Tier::RewardMultiplier.new.get(100)

    { lowest: lowest, highest: highest}
  end
end

app/views/shared/partials/campaigns/_campaign_card.html.slim
.ui.segment.campaign-card 
  .image-panel
  // Image Size 400 x 400
  = image_tag campaign.image, class: 'ui fluid image'
  .ui.vertical.segment.content-panel
    p.campaign-title= campaign.title.upcase
    .spacing-top
      .rewards
        - reward = reward_range(campaign)
        span Earn 
        span.bold= "#{reward[:lowest]} - #{reward[:highest]}MYR"
      .timer
        p= campaign.time_remaining 

app/views/shared/partials/campaigns/_index.html.slim
#campaigns-list  
  .ui.stackable.four.column.grid
    - campaigns.each do |campaign|
      .column
        = link_to campaign_path(campaign.id) do
          .campaign-card 
            .ui.segment.zero-padding
              .image-panel
                = image_tag "http://placehold.it/720x720", class: 'ui fluid image'
              .ui.vertical.segment.content-panel
                p.campaign-title= campaign.title
                p.campaign-description= truncate(campaign.description, length: 100)
                .ui.two.column.grid.spacing-top
                  .column
                    .rewards
                      span Earn 
                      span.bold 50 - 100 MYR
                  .column.timer
                    p= campaign.time_remaining

app/views/shared/partials/campaigns/_panels.html.slim
#campaigns-list  
  .ui.stackable.four.column.grid
    - campaigns.each do |campaign|
      .column
        - if current_user
          = link_to campaign_path(campaign.id)
            = render partial: 'shared/partials/campaigns/campaign_card', locals: { campaign: campaign }
        - else
          = link_to campaign_path(campaign.id), remote: true, id: 'scroll-to-campaign'
            = render partial: 'shared/partials/campaigns/campaign_card', locals: { campaign: campaign }
          

app/views/shared/partials/campaigns/_show.html.slim
p= "Title: #{campaign.title}"

p= "Description: #{campaign.description}"

p= "Starting date: #{campaign.start_date}"

p= "Ending date: #{campaign.end_date}"

p= "Categories: #{campaign.category_list}"

- if campaign.topics.present?
 - campaign.topics.each do |topic|
  .spacing
  p= "Topic media platform: #{topic.social_media_platform}"
  p=
  p= "Topic description: #{topic.description}"
  p= "Topic posts required: #{topic.num_of_posts}"
  p= "Topic likes required: #{topic.num_of_likes}"
  p= "Topic comments required: #{topic.num_of_comments}"
  -if !admin?
    p = link_to "Share this!", new_campaign_topic_post_path(@campaign, topic)