config/routes.rb
Rails.application.routes.draw do

  #Root
  root 'home#traffic_control'

  #Landing
  get "landing", to: "home#landing", as: :landing

  #Campaigns
  resources :campaigns do
    resources :topics do
      resources :posts, except: [:edit]
      resources :user_images
    end
  end

  #Contact
  post 'contact', to: 'contacts#create'
  
  #Users
  get 'warpgate', to: 'user_sessions#new', as: :warpgate
  post 'logout', to: 'user_sessions#destroy', as: :logout
  resources :users
  resources :user_sessions, except: [:update, :edit]
  resources :password_resets

  #Participated Campaigns
  get 'participated', to: 'participated_campaigns#index', as: :participated

  #Oauth
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  delete "oauth/:provider", to: "oauths#destroy", as: :delete_oauth

  #Admin Panel
  namespace :admin do
    get 'dashboard', to: 'dashboard#index', as: :dashboard
    resources :options, only: [:edit, :update]
    resources :reward_transactions, only: [:edit, :update]
    resources :featureds
    resources :campaigns do
      resources :topics
    end
    resources :announcements
    resources :users
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < AdminController
  def index
    @campaigns = CampaignDecorator.wrap(Campaign.all)
    @featured_campaigns = FeaturedCampaignDecorator.wrap(Featured.where(featurable_type: "Campaign").limit(12))
    @new_featured_campaign = Featured.new
    @options = Option.first
    @transactions = RewardTransaction.all
  end
end

app/views/admin/dashboard/index.html.slim
#admin-dashboard.ui.grid
  .row.center
    .sixteen.wide.column
      h1 Admin Dashboard

  .row.center
    #admin-sidebar.four.wide.column.center
      p MENU OPTIONS 
      p = link_to 'NEW USER', new_admin_user_path
      p = link_to 'SHOW USERS', admin_users_path
      p = link_to 'NEW CAMPAIGN', new_admin_campaign_path
      p = link_to 'SHOW CAMPAIGNS', admin_campaigns_path
      p = link_to "LOGOUT", :logout, method: :post
    
    .eight.wide.column
      #featured-campaigns
        p.center FEATURED CAMPAIGNS

        table.ui.celled.striped.table
          thead
            tr
              th
                p Index
              th
                p Reference
              th
                p Title
              th
                p Actions
          tbody
            - @featured_campaigns.each_with_index do |campaign, i|
              tr
                td.collapsing
                  p= i + 1
                td.collapsing
                  p= "#{campaign.refcode}"
                td
                  p= "#{campaign.title}"
                td.collapsing
                  = link_to "Delete", [:admin, campaign.featured], method: :delete, data: { confirm: "Unfeature Campaign?"}
          tfoot.full-width
            tr
              th colspan="4"
                = form_for [:admin, @new_featured_campaign] do |f|
                  = f.select :featurable_id, options_from_collection_for_select(@campaigns, "id", "refcode"), {}, { class: "ui fluid search dropdown featured-field spacing-top" }
                  = f.hidden_field :featurable_type, value: "Campaign"
                  p.center= f.submit "Feature Campaign"

      #category-options
        p.center ALLOWABLE CATEGORIES
        p.center= "(Click to edit)"
        p.center Separate categories using comma

        #category-edit-activator.ui.segment
          .ui.form
            p= best_in_place @options, :category_list, as: :textarea, url: admin_option_path(@options), class: 'field', activator: '#category-edit-activator'

  .row.center
    .twelve.wide.column
      #rewards-table
        p.center REWARDS TRANSACTIONS

        table.ui.celled.striped.table
          thead
            tr
              th
                p NO
              th
                p ID
              th
                p USER EMAIL
              th
                p CAMPAIGN REFCODE
              th
                p AMOUNT
              th
                p PAID?
              th
                p CREATED AT
              th
                p ADMIN ACTION

          tbody
            - @transactions.each_with_index do |transaction, i|
              tr
                td
                  p= i
                td
                  p= transaction.id
                td
                  p= transaction.user.email
                td
                  p= transaction.campaign.refcode
                td
                  p= transaction.amount
                td
                  p= transaction.paid
                td
                  p= transaction.created_at
                td
                  - if transaction.paid?
                    = form_for [:admin, transaction] do |f|
                      = f.hidden_field :paid, value: false
                      = f.submit "Unpaid", data: { confirm: "Set status to paid?" }
                  - else
                    = form_for [:admin, transaction] do |f|
                      = f.hidden_field :paid, value: true
                      = f.submit "Paid", data: { confirm: "Set status to unpaid?" }