config/routes.rb
Rails.application.routes.draw do

  #Root
  root 'home#traffic_control'

  #Landing
  get "landing", to: "home#landing", as: :landing

  #Campaigns
  resources :campaigns do
    resources :topics do
      resources :posts, except: [:edit]
      resources :user_images
    end
  end

  #Contact
  post 'contact', to: 'contacts#create'
  
  #Users
  get 'warpgate', to: 'user_sessions#new', as: :warpgate
  post 'logout', to: 'user_sessions#destroy', as: :logout
  resources :users
  resources :user_sessions, except: [:update, :edit]
  resources :password_resets

  #Participated Campaigns
  get 'participated', to: 'participated_campaigns#index', as: :participated

  #Oauth
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  delete "oauth/:provider", to: "oauths#destroy", as: :delete_oauth

  #Admin Panel
  namespace :admin do
    get 'dashboard', to: 'dashboard#index', as: :dashboard
    resources :options, only: [:edit, :update]
    resources :reward_transactions, only: [:edit, :update]
    resources :featureds
    resources :campaigns do
      resources :topics
    end
    resources :announcements
    resources :users
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def traffic_control
    if current_user && current_user.admin?
      redirect_to admin_dashboard_path 
    elsif current_user
      redirect_to user_path(current_user)
    else
      redirect_to landing_path
    end
  end
  
  def landing
    @contact = Contact.new
    @campaigns = FeaturedCampaignDecorator.wrap(Featured.where(featurable_type: "Campaign").limit(12))
  end
end

app/views/home/_about.html.slim
#about-us.none
  h2.center AN INFLUENCER AT HEART?
  h2.subtitle This is what it takes to be an influencer

  .ui.stackable.three.column.grid
    
    .column.center
      .image-panel
        = image_tag "landing/flaunt.png", class: 'ui centered fluid medium image'
      .content-panel
        p.title Flaunt It
        p.subtitle Our influencers have their own niche - just like you! If you're looking for influencers who are the perfect fit, they're all here.
    
    .column.center
      .image-panel
        = image_tag "landing/tell.png", class: 'ui centered fluid medium image'
      .content-panel
        p.title Tell It
        p.subtitle With great power, comes great responsibility. Now that you have the followers, we need your help to share these stories to your followers. Are you up for it?
    
    .column.center
      .image-panel
        = image_tag "landing/spend.png", class: 'ui centered fluid medium image'
      .content-panel
        p.title Spend It
        p.subtitle Just by sharing stories that are close to your heart, you get to earn some extra moolah! How about that?

  .ui.one.column.grid.padding-top-5.padding-bottom-5.desktop
    .column.center
      span= link_to "BROWSE!", '#staging-container',"data-scroll": true, class: "about-browser ui black basic button campaign-button"
      span.space-em-up OR
      span= link_to "CONNECT NOW!", '#', class: "ui black basic button connect-button trigger-connect"
      br
      br
      span.small-padding-top Got a question? 
      = link_to "Talk to us!", '#contact-us', "data-scroll": true

  .ui.one.column.grid.padding-top-5.padding-bottom-5.mobile
    .column.center
      p= link_to "BROWSE!", '#staging-container',"data-scroll": true, class: "about-browser ui black basic button campaign-button"
      p OR
      span= link_to "CONNECT NOW!", '#', class: "ui black basic button connect-button trigger-connect"
      br
      br
      span.small-padding-top Got a question? 
      = link_to "Talk to us!", '#contact-us', "data-scroll": true

  .ui.stackable.three.column.grid
    
    .column.center
      .image-panel
        = image_tag "landing/find.png", class: 'ui centered fluid medium image'
      .content-panel
        p.title Find Them
        p.subtitle Our influencers have their own niche - just like you! If you're looking for influencers who are the perfect fit, they're all here.
    
    .column.center
      .image-panel
        = image_tag "landing/use.png", class: 'ui centered fluid medium image'
      .content-panel
        p.title Use Them
        p.subtitle Create stories on the webapp and our influencers will help you share the stories to their friends and followers.
    
    .column.center
      .image-panel
        = image_tag "landing/assess.png", class: 'ui centered fluid medium image'
      .content-panel
        p.title Assess Them
        p.subtitle You'll get real-time reporting on your stories as our influencers share them. See how they're engaging with their fans, and getting their fans to check out your story!

  .ui.one.column.grid.padding-top-5
    .column.center
      p= link_to "I'M INTERESTED!", '#', class: "ui black basic button connect-button"
      br
      span.small-padding-top Got a question? 
      = link_to "Talk to us!", '#contact-us', "data-scroll": true
      

app/views/home/_connect.html.slim
#connect-modal.ui.modal
  i.close.icon
  .header.center
    p.super-title CONNECT
  .modal-content
    .content
      .description
        p.title.padding-bottom-4 You’re just a click away to view our top influencers! Join us and you can be an influencer too!
        .center
          p = link_to auth_at_provider_path(provider: :facebook), class: "ui facebook button capitalize social-buttons" do 
              = semantic_icon(:facebook)
              = "Connect with Facebook"
          p.padding-bottom-4 = link_to auth_at_provider_path(provider: :twitter), class: "ui twitter button capitalize social-buttons"do
              = semantic_icon(:twitter)
              = "Connect with Twitter"
        p.subtitle.padding-bottom-4 We promise we will not post anything to your account without your permission. By connecting, you agree to our Terms of Use and Privacy Policy.

app/views/home/_contact_form.html.slim
= form_for contact, url: contact_path, method: :post, html: { class: 'ui small fluid form spacing-bottom', id: 'contact_form' } do |f|
  #contact-us-title.hide
    p.left DROP US A NOTE!
  .two.fields.small-spacing-top
    #contact-left.field.hide
      .two.fields
        .field
          label.white MY NAME IS
          = f.text_field :name, placeholder: 'Name'
        .field
          label.white#options-user-type I AM A / AN
          = f.select :type, options_for_select([["Advertiser", "Advertiser"], 
                                                ["User", "User"]], "User"), {}, { class: 'ui selection dropdown' }
      .field
        label.white MY EMAIL IS
        = f.email_field :email, placeholder: 'Email address'

    #contact-right.field.hide
      label.white MESSAGE
      = f.text_area :content, cols: 50, rows: 10
      = f.submit "SEND", class: "button-settings ui button", id: "contact-submit", placeholder: 'Hey there!'

app/views/home/_info_banner.html.slim
.column.center
  .ui.two.column.grid
    .equal.height.row
      .column.image-alignment
        = image_tag "landing/browse.png", class: 'image-settings'
      .column.v-padding
        p.subtext Browse Campaigns..
.column.center
  .ui.two.column.grid
    .equal.height.row
      .column.image-alignment
        = image_tag "landing/share.png", class: 'image-settings'
      .column.v-padding 
        p.subtext Talk about it?
.column.center
  .ui.two.column.grid
    .equal.height.row
      .column.image-alignment
        = image_tag "landing/reward.png", class: 'image-settings'
      .column.v-padding
        p.subtext Get Rewarded!

app/views/home/index.html.slim
#hero-banner.module.parallax
  .hero-content
    h1.banner-title.hide
      | Viral Vial is about 
      span.purple data-typer-targets="reaching out, socializing, engagement, sharing, empowering" socializing
      p.mobile.purple data-typer-targets="reaching out, socializing, engagement, sharing, empowering" socializing
    .arrow-down
      = link_to "#staging-container", "data-scroll": true
        = image_tag "landing/triangle.png"

section#info-banner
  .content
    .ui.grid.center.aligned
      .twelve.wide.column
        .ui.stackable.three.column.grid
          = render partial: 'info_banner'

section.staging-grounds
  
  .ui.grid.center
    .twelve.wide.column
      #staging-container
        #campaign-partial-container.none
        #campaigns-list-container
          h2.left#featured-campaigns-waypoint OUR FEATURED CAMPAIGNS
          h2.left.subtitle Take a peek at our current trending campaigns!
          = render partial: 'shared/partials/campaigns/panels', locals: { campaigns: @campaigns }
        = render partial: 'about'


#contact-us.zero
  .ui.page.stackable.grid
    .column
      = render partial: "contact_form", locals: { contact: @contact }
                                
= render partial: 'connect'

app/views/home/landing.html.slim
#hero-banner.module.parallax
  .hero-content
    h1.banner-title.hide
      | Viral Vial is about 
      span.purple data-typer-targets="reaching out, socializing, engagement, sharing, empowering" socializing
      p.mobile.purple data-typer-targets="reaching out, socializing, engagement, sharing, empowering" socializing
    .arrow-down
      = link_to "#staging-container", "data-scroll": true
        = image_tag "landing/triangle.png"

section#info-banner
  .content
    .ui.grid.center.aligned
      .twelve.wide.column
        .ui.stackable.three.column.grid
          = render partial: 'info_banner'

section.staging-grounds
  
  .ui.grid.center
    .fourteen.wide.column
      #staging-container
        #campaign-partial-container.none
        #campaigns-list-container
          h2.left#featured-campaigns-waypoint OUR FEATURED CAMPAIGNS
          h2.left.subtitle Take a peek at our current trending campaigns!
          = render partial: 'shared/partials/campaigns/panels', locals: { campaigns: @campaigns }
        = render partial: 'about'

#contact-us.zero
  .ui.page.stackable.grid
    .column
      = render partial: "contact_form", locals: { contact: @contact }
                                
= render partial: 'connect'