config/routes.rb
Rails.application.routes.draw do

  #Root
  root 'home#traffic_control'

  #Landing
  get "landing", to: "home#landing", as: :landing

  #Campaigns
  resources :campaigns do
    resources :topics do
      resources :posts, except: [:edit]
      resources :user_images
    end
  end

  #Contact
  post 'contact', to: 'contacts#create'
  
  #Users
  get 'warpgate', to: 'user_sessions#new', as: :warpgate
  post 'logout', to: 'user_sessions#destroy', as: :logout
  resources :users
  resources :user_sessions, except: [:update, :edit]
  resources :password_resets

  #Participated Campaigns
  get 'participated', to: 'participated_campaigns#index', as: :participated

  #Oauth
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  delete "oauth/:provider", to: "oauths#destroy", as: :delete_oauth

  #Admin Panel
  namespace :admin do
    get 'dashboard', to: 'dashboard#index', as: :dashboard
    resources :options, only: [:edit, :update]
    resources :reward_transactions, only: [:edit, :update]
    resources :featureds
    resources :campaigns do
      resources :topics
    end
    resources :announcements
    resources :users
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  authenticates_with_sorcery!

  after_initialize :set_default_password, if: :new_record?
  before_validation :set_default_email, if: :new_record?

  enum role: [:user, :superadmin, :admin, :banned]
  enum gender: [:unspecified, :female, :male]
  enum race: [:chinese, :indian, :malay, :others]

  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end

  validates :password, length: { minimum: 8 }, if: :password
  validates :password, confirmation: true, if: :password
  validates :password_confirmation, presence: true, if: :password
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validate :correct_user_birthday
  validates_size_of :image, maximum: 5.megabytes, messaage: 'should be less than 5MB'

  acts_as_taggable_on :primary_interests, :secondary_interests

  has_many :authentications, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :reward_transactions
  has_one :user_image, dependent: :destroy
  has_one :social_score, dependent: :destroy
  accepts_nested_attributes_for :authentications

  mount_uploader :image, ImageUploader

  # Move to concerns
  scope :admin_order, ->(attr, direction) {
    Admin::SortUsers.new(attr, direction).scope
  }

  def interest_not_selected?
    primary_interest_list.empty?
  end

  def set_access_token(access_token, provider)
    auth = authentications.find_by(provider: provider)
    auth.update(token: access_token.try(:token), secret: access_token.try(:secret))
  end
  
  def main_interest=(value)
    self.primary_interest_list = value
  end

  def birthday_day=(value)
    self.birthday = birthday.change(day: value.to_i)
  end

  def birthday_month=(value)
    self.birthday = birthday.change(month: value.to_i)
  end

  def birthday_year=(value)
    self.birthday = birthday.change(year: value.to_i)
  end

  private

  def correct_user_birthday
    begin
      return if DateTime.parse(birthday.to_s) && birthday <= Date.today
    rescue
    end
    errors.add(:birthday, 'is invalid')
  end

  def set_default_email
    return unless self.email.nil?
    self.email = loop do
      email = "#{SecureRandom.urlsafe_base64}@changeme.com"
      break email unless User.where(email: email).exists?
    end
  end

  def set_default_password
    return unless self.password.nil?
    password = SecureRandom.hex
    self.password = password
    self.password_confirmation = password
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :set_user, except: [:index, :new]

  def new
    @user = User.new
  end

  def edit
  end

  def update
  end

  def create
    @user = User.new(user_params.merge(role: "admin"))

    if @user.save
      flash[:notice] = "New user created"
      redirect_to admin_user_path(@user)
    else
      flash[:error] = "Error!"
      render :new
    end
  end

  def index
    @users = User.admin_order(params[:sort], params[:direction])
  end

  def destroy
    if @user.destroy
      flash[:notice] = "User deleted"
      redirect_to admin_users_path
    else
      flash[:error] = "error :#{@user.errors.full_messages}"
      redirect_to @user
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, :require_login
  respond_to :html, :js, :json

  def show
    @providers = ['facebook', 'twitter']
    respond_with(@user)
  end

  def edit
  end

  def update
    @user.update(user_params)
    respond_with(@user)
  end
  
  private

  def set_user
    user = User.find(params[:id])
    authorize user
    @user = UserDecorator.new(user)
  end

  def user_params
    params.require(:user).permit(:email, :password, :blog_url, :image,
                                 :password_confirmation, :name,
                                 :birthday, :birthday_day, :birthday_month, :birthday_year, 
                                 :gender, :race, :religion, :contact_number, :nationality, :location, :country,
                                 :marital_status, :role, :main_interest, :secondary_interest_list,
                                 authentication_attributes: [])
  end
end

app/helpers/user_helper.rb
module UserHelper
  def render_direction
    case params[:direction]
    when 'desc'
      'asc'
    when 'asc'
      'desc'
    else
      'asc'
    end
  end

  def user_has_updated_interest?
    current_user && current_user.try(:interest_not_selected?)
  end
  
  def user_linked_provider?(provider)
    true if current_user.authentications.find_by(provider: provider)
  end

  def user_has_not_posted?(campaign)
    current_user.posts.where(campaign_id: campaign.id).count == 0
  end

  def total_reward_amount
    amount = current_user.reward_transactions.pluck(:amount)

    amount.sum || 0
  end
end

app/views/admin/users/edit.html.slim
h1 Editing user

.ui.grid
  .row
    .sixteen.wide.column
      = render partial: '/shared/partials/users/edit_profile_form', locals: { title: "Edit user", user: [:admin, @user] }

      = link_to 'Show', @user
      '
      = link_to 'Back', admin_users_path

app/views/admin/users/index.html.slim
.users.index.ui.grid.center
  .fourteen.wide.column
    h1 Listing users
    = link_to "Back to control panel", admin_dashboard_path
      
    table.ui.celled.striped.table
      thead
        tr
          th 
            p= link_to 'Email', url_for(sort: 'email', direction: render_direction)
          th 
            p= link_to 'Followers', url_for(sort: 'followers', direction: render_direction)
          th 
            p= link_to 'Viral Score', url_for(sort: 'viral', direction: render_direction)
          th colspan="3"
            p Admin Actions

      tbody
        - @users.each do |user|
          tr
            td
              p= user.email
            td 
              p= user.social_score.total_followers
            td 
              p= user.social_score.viral_score
            td 
              p= link_to 'Show', [:admin, user]
            td 
              p= link_to 'Edit', edit_admin_user_path(user)
            td 
              p= link_to 'Destroy', [:admin, user], data: {:confirm => 'Are you sure?'}, :method => :delete

    br

    = link_to 'New User', new_admin_user_path

app/views/admin/users/new.html.slim
#admin-user-new.ui.grid
  .row.center
    .fourteen.wide.column
      h1 Create New user
      = link_to "Back to admin panel", admin_dashboard_path

      .container

        .col-md-6
          = form_for [:admin, @user] do |f|
            - if @user.errors.any?
              #error_explanation
                h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
                ul
                  - @user.errors.full_messages.each do |message|
                    li = message

            .spacing.space-out
              = f.label "#{:email}:"
              = f.email_field :email, autofocus: true, placeholder: 'Enter email here'

            .spacing.space-out
              = f.label "#{:password}:"
              = f.password_field :password

            .spacing.space-out
              = f.label "#{:password_confirmation}:"
              = f.password_field :password_confirmation

            .spacing.space-out
                p= f.submit 'Save'

app/views/admin/users/show.html.slim
= render partial: '/shared/partials/users/show', locals: { user: [:admin, @user] }